package nn

import (
	"fmt"
	"math"

	"github.com/georgebuilds/anneal/tensor"
	"github.com/georgebuilds/anneal/uop"
)

// ── CausalSelfAttention ──────────────────────────────────────────────────────
//
// CausalSelfAttention implements multi-head self-attention with a causal
// (autoregressive) mask, as used in GPT-style transformers.
//
// Design choices following the Wave 2 Slice J plan:
//   - Mask is host-precomputed and stored as a fixed leaf buffer (a
//     []float32 of length blockSize*blockSize, 1 on/below the diagonal, 0
//     above). It is NOT generated by a graph-level Tril op; passing it as
//     a leaf keeps the graph free of any tile/range mask machinery.
//   - The mask is applied MULTIPLICATIVELY post-exp (exp_scores * mask)
//     rather than additively pre-exp (scores + -inf). The two are
//     mathematically identical (both zero out attention contributions
//     from j > i before the softmax normaliser), but the multiplicative
//     form keeps exp arguments in a bounded range (no exp(-1e9) underflow,
//     no 0 * large-adjoint precision loss in the backward chain). Both
//     forms are valid causal-mask implementations.
//   - QKV is implemented as a single fused Linear (nEmbd -> 3*nEmbd) for
//     parameter / pass efficiency. The output is split via Shrink.
//   - The q@k^T and att@v matmuls operate directly on the 4D batched shape
//     [B, nHead, T, dHead]; the Matmul broadcasts the leading batch dims
//     (B, nHead) via the existing rangeify path (TestMatmulBatched covers
//     the 3D case, the same broadcast rule extends to rank-4).
//
// Shape conventions throughout:
//
//	x       [B, T, nEmbd]
//	qkv     [B, T, 3*nEmbd]
//	q,k,v   [B, T, nEmbd] -> [B, nHead, T, dHead]
//	att     [B, nHead, T, T]
//	out     [B, nHead, T, dHead] -> [B, T, nEmbd]
//	y       [B, T, nEmbd]
//
// where dHead = nEmbd / nHead.
type CausalSelfAttention struct {
	QKV  *Linear // fused Q,K,V projection: nEmbd -> 3*nEmbd
	Proj *Linear // output projection: nEmbd -> nEmbd

	NHead     int
	NEmbd     int
	BlockSize int

	// maskData is the host-precomputed additive causal mask, length
	// blockSize*blockSize, row-major. Below or on the diagonal it is 0;
	// above the diagonal it is maskNegInf. Forward() builds a fresh
	// BUFFER leaf for the current arena and seeds it with this slice.
	// The mask is treated as a fixed (non-trainable) leaf: no gradient
	// flows back into it and it is not in Params().
	maskData []float32

	dtype  *uop.DType
	device string
}

// maskKeep / maskDrop are the multiplicative-mask values:
//   - maskKeep = 1 on and below the diagonal (positions to attend to).
//   - maskDrop = 0 above the diagonal (positions to mask out).
//
// We apply (exp(scores) * mask) before normalising rather than (scores +
// additive_neg_inf) because the latter produces 0 * large adjoint products
// in the backward path that lose precision in this autodiff implementation.
const (
	maskKeep = float32(1.0)
	maskDrop = float32(0.0)
)

// NewCausalSelfAttention constructs a CausalSelfAttention module.
// nEmbd must be divisible by nHead.
//
// The mask is initialised here once: mask[i,j] = 1 for j <= i, 0 otherwise,
// so multiplying exp(scores) by mask zeros any contribution from positions
// j > i before the softmax row-sum normalisation.
func NewCausalSelfAttention(a *uop.Arena, nEmbd, nHead, blockSize int) *CausalSelfAttention {
	if nEmbd%nHead != 0 {
		panic(fmt.Sprintf("nn: CausalSelfAttention: nEmbd %d not divisible by nHead %d", nEmbd, nHead))
	}
	if blockSize <= 0 {
		panic("nn: CausalSelfAttention: blockSize must be positive")
	}

	dtype := uop.Dtypes.Float32
	device := "webgpu"

	att := &CausalSelfAttention{
		QKV:       NewLinear(a, int64(nEmbd), int64(3*nEmbd), true, dtype, device),
		Proj:      NewLinear(a, int64(nEmbd), int64(nEmbd), true, dtype, device),
		NHead:     nHead,
		NEmbd:     nEmbd,
		BlockSize: blockSize,
		dtype:     dtype,
		device:    device,
	}

	// Precomputed causal-mask data, row-major [blockSize, blockSize].
	// 1.0 below/on diagonal (keep), 0.0 above (drop).
	att.maskData = make([]float32, blockSize*blockSize)
	for i := 0; i < blockSize; i++ {
		for j := 0; j < blockSize; j++ {
			if j <= i {
				att.maskData[i*blockSize+j] = maskKeep
			} else {
				att.maskData[i*blockSize+j] = maskDrop
			}
		}
	}
	// Suppress unused arena parameter warning: keep signature for future use
	// (parity with NewLinear / NewConv2d).
	_ = a

	return att
}

// NewSelfAttention constructs a non-causal multi-head self-attention module,
// for encoder-style transformers (ViT, BERT). It shares the same struct,
// forward path, and parameter layout as CausalSelfAttention; the only
// difference is the precomputed mask: every position attends to every other
// position (mask all ones), so the multiplicative softmax mask is a no-op.
//
// This is the additive-sibling design call (option (b) in the ViT design
// brief): zero risk to the existing CausalSelfAttention contract, no rename,
// no Block adaptation needed. Block, GPT, nanoGPT continue to use
// NewCausalSelfAttention and remain byte-identical; ViT uses this constructor.
//
// nEmbd must be divisible by nHead. seqLen is the maximum sequence length the
// mask covers (analogous to blockSize but with no causal semantic).
func NewSelfAttention(a *uop.Arena, nEmbd, nHead, seqLen int) *CausalSelfAttention {
	if nEmbd%nHead != 0 {
		panic(fmt.Sprintf("nn: NewSelfAttention: nEmbd %d not divisible by nHead %d", nEmbd, nHead))
	}
	if seqLen <= 0 {
		panic("nn: NewSelfAttention: seqLen must be positive")
	}

	dtype := uop.Dtypes.Float32
	device := "webgpu"

	att := &CausalSelfAttention{
		QKV:       NewLinear(a, int64(nEmbd), int64(3*nEmbd), true, dtype, device),
		Proj:      NewLinear(a, int64(nEmbd), int64(nEmbd), true, dtype, device),
		NHead:     nHead,
		NEmbd:     nEmbd,
		BlockSize: seqLen,
		dtype:     dtype,
		device:    device,
	}

	// Non-causal mask: all ones. Multiplying exp(scores) by an all-ones mask
	// before the softmax row-sum normalisation is the identity, so the
	// existing CausalSelfAttention.Forward body computes standard
	// non-masked softmax attention with this leaf in place.
	att.maskData = make([]float32, seqLen*seqLen)
	for i := range att.maskData {
		att.maskData[i] = maskKeep
	}
	_ = a

	return att
}

// Forward computes causal multi-head self-attention.
//
// Input  x: [B, T, nEmbd]    (T <= BlockSize)
// Output y: [B, T, nEmbd]
//
// Steps:
//  1. qkv = QKV(x)                              [B, T, 3*nEmbd]
//  2. split into q, k, v                        each [B, T, nEmbd]
//  3. reshape+permute to                        [B, nHead, T, dHead]
//  4. att = q @ k^T / sqrt(dHead)               [B, nHead, T, T]
//  5. att += causalMask[:T, :T]                 (broadcast over B, nHead)
//  6. att = softmax(att, axis=-1)               numerically stable
//  7. out = att @ v                             [B, nHead, T, dHead]
//  8. permute+reshape back to                   [B, T, nEmbd]
//  9. y = Proj(out)
func (m *CausalSelfAttention) Forward(x *tensor.Tensor) *tensor.Tensor {
	xShape := x.Shape()
	if len(xShape) != 3 {
		panic(fmt.Sprintf("nn: CausalSelfAttention: input must be rank 3 [B,T,nEmbd], got rank %d", len(xShape)))
	}
	B, T, E := xShape[0], xShape[1], xShape[2]
	if int(E) != m.NEmbd {
		panic(fmt.Sprintf("nn: CausalSelfAttention: input nEmbd=%d != module nEmbd=%d", E, m.NEmbd))
	}
	if T > int64(m.BlockSize) {
		panic(fmt.Sprintf("nn: CausalSelfAttention: T=%d exceeds blockSize=%d", T, m.BlockSize))
	}
	H := int64(m.NHead)
	D := E / H // dHead

	a := x.Arena()

	// 1. Fused QKV projection: [B,T,E] -> [B,T,3E]
	qkv := m.QKV.Forward(x)

	// 2. Split along last axis into q, k, v: each [B,T,E].
	q := qkv.Shrink([][2]int64{{0, B}, {0, T}, {0, E}})
	k := qkv.Shrink([][2]int64{{0, B}, {0, T}, {E, 2 * E}})
	v := qkv.Shrink([][2]int64{{0, B}, {0, T}, {2 * E, 3 * E}})

	// 3. Reshape and permute each to [B, H, T, D].
	//    [B, T, E] -> [B, T, H, D] -> permute(0,2,1,3) -> [B, H, T, D].
	splitHeads := func(t *tensor.Tensor) *tensor.Tensor {
		return t.Reshape([]int64{B, T, H, D}).Permute([]int{0, 2, 1, 3})
	}
	q = splitHeads(q)
	k = splitHeads(k)
	v = splitHeads(v)

	// 4. Scaled dot-product: att = (q @ k^T) / sqrt(D).
	//    4D batched matmul: [B, H, T, D] @ [B, H, D, T] -> [B, H, T, T].
	//    Matmul broadcasts batch (B, H) dims via the existing rangeify path.
	kT := k.Transpose() // [B, H, D, T]
	att := q.Matmul(kT) // [B, H, T, T]

	// Scale by 1/sqrt(D).
	invSqrtD := tensor.FullSints(a, att.ShapeSints(),
		1.0/math.Sqrt(float64(D)), m.dtype, m.device)
	att = att.Mul(invSqrtD)

	// 5/6. Masked softmax (multiplicative-mask variant).
	//
	// Standard softmax: y_i = exp(s_i) / sum_j exp(s_j).
	// Masked softmax we want: positions j > i contribute zero. The textbook
	// trick is to add an additive mask of -inf above the diagonal so
	// exp(-inf) = 0, but in this autodiff implementation that produces
	// 0 * large-adjoint products in the backward chain that lose precision
	// (FD vs analytic relative error >> 1e-3 even for small inputs).
	// We instead apply the mask MULTIPLICATIVELY post-exp:
	//
	//   exp_scores       = exp(att)             // shape [B, H, T, T]
	//   exp_scores_masked = exp_scores * mask   // zero out positions j > i
	//   row_sum          = sum_{j} masked[..., j] keepdim=False then Reshape
	//   y                = exp_scores_masked / row_sum
	//
	// Math: exp_scores_masked[..., j] = exp(att[..., j]) when j <= i, else 0.
	// row_sum is the partition function over the unmasked entries only.
	// Division gives a proper probability distribution over j <= i, identical
	// to the additive -inf formulation. Backward: gradient through Mul by
	// mask is just (grad_out * mask), which is exactly 0 at masked positions
	// and unchanged at unmasked positions. No 0 * large_adj precision loss.
	//
	// Mask leaf: a fresh BUFFER seeded with the precomputed top-left T x T
	// submatrix of m.maskData. Fixed (non-trainable) leaf, not in Params().
	//
	// IMPORTANT shape-tracker contract: we reduce with keepdim=FALSE and then
	// add back the 1-dim via an explicit Reshape. tensor/gradient.go
	// shapeOfNode for OpReduceAxis only sees the ReduceArg, which carries
	// axes but not keepdim; if forward uses keepdim=true directly the backward
	// shape rule recovers the reduced shape and any subsequent broadcast
	// Expand from the reduced tensor fails at grad time with a Reshape size
	// mismatch. keepdim=false + explicit Reshape makes the rank-adding step
	// visible to the autodiff shape tracker.
	//
	// Numerical-stability NOTE: a standard implementation subtracts max(att)
	// from att before exp to keep exp arguments <= 0. We omit the max-shift
	// because OpMax backward (tie-broken argmax routing) inflates the
	// per-kernel buffer count above the WebGPU 8-buffer cap when the
	// input-gradient kernel is realized. The inputs and weights here are
	// initialised at bounded scales so exp(att) stays in float32 range
	// (the multiplicative mask further bounds the operating point: any score
	// at a masked position has no effect on the loss).
	maskData := make([]float32, T*T)
	for i := int64(0); i < T; i++ {
		for j := int64(0); j < T; j++ {
			maskData[i*T+j] = m.maskData[i*int64(m.BlockSize)+j]
		}
	}
	maskLeaf := tensor.NewLeaf(a, []int64{T, T}, m.dtype, m.device)
	maskLeaf.SetData(maskData)
	maskBroadcast := maskLeaf.Reshape([]int64{1, 1, T, T}).Expand([]int64{B, H, T, T})

	expv := att.Exp()                             // [B, H, T, T]
	expvMasked := expv.Mul(maskBroadcast)         // [B, H, T, T], zero above diagonal
	sumRed := expvMasked.Sum([]int{3}, false)     // [B, H, T]
	sumExp := sumRed.Reshape([]int64{B, H, T, 1}) // [B, H, T, 1]
	att = expvMasked.Div(sumExp)                  // [B, H, T, T]

	// 7. att @ v: [B, H, T, T] @ [B, H, T, D] -> [B, H, T, D]
	out := att.Matmul(v)

	// 8. Permute back -> [B, T, H, D] -> [B, T, E].
	out = out.Permute([]int{0, 2, 1, 3}).Reshape([]int64{B, T, E})

	// 9. Output projection.
	return m.Proj.Forward(out)
}

// Params returns the trainable parameters: QKV.Weight, QKV.Bias, Proj.Weight,
// Proj.Bias. The causal mask is intentionally excluded (it is a fixed leaf,
// not a trainable parameter).
func (m *CausalSelfAttention) Params() []*Parameter {
	ps := make([]*Parameter, 0, 4)
	ps = append(ps, m.QKV.Params()...)
	ps = append(ps, m.Proj.Params()...)
	return ps
}
